# Note that all parameters in this file are lists, for multiple cameras
# simply add more elements to each list ensuring that the order of the
# parameters is maintained

# Serial Numbers of Cameras
camera_serial_nums: ["19423295"]
# Names of Cameras (used for topic names, etc)
camera_names: ["cam0"]
# Paths to Camera info files
camera_info_paths: ["package://spinnaker_driver/camera_info/blackfly.yaml"]

# Publish Mono Images Flag : True = Mono8, False = BGR8
mono_flags: [false]

# Is the camera triggered? True = Line0, False = FrameRate
is_triggered_flags: [false]
# Time in microseconds between when the camera receives a trigger and when exposure begins for the image
# GigE Cameras: 13.0
# USB3 Cameras: 24.0
trigger_delays: [24.0]
# Frame Rate if not triggered
fps: [20.0]

# Use Auto Exposure flag
is_auto_exp_flags: [true]
# Auto Exposure Bounds if using Auto Exposure (max: 3e7 uSecs)
max_auto_exp: [10000.0]
# Auto Exposure Bounds if using Auto Exposure (min: 12 uSecs)
min_auto_exp: [50.0]
# Fixed Exposure if not Auto (uSecs)
fixed_exp: [10000.0]
# 0 Gain / 1 ExposureTime
auto_exposure_priority: [0]

# Use Auto Gain Flag
auto_gains: [true]
# Gain Bounds if using Auto Gain (max: 47.99 dB)
max_gains: [20.0]
# Gain Bounds if using Auto Gain (min: 0.0 dB)
min_gains: [0.0]
# Fixed Gain if not Auto Gain
gains: [5.0]

# Enable Gamma Correction
enable_gamma: [true]
# Gamma setting if using Gamma Correction
gammas: [0.8]

# Binning Value (decimate image resolution by x)
binnings: [1]
# 0 Average / 1 Sum
binning_mode: [1]

# Enable Exposure Time Compensation
exp_comp_flags: [true]

# 0 Normal / 1 backlight / 2 Frontlight
lighting_mode: [0]

# Device Link Throughput Limits
# GigE Cameras: 40325200
# USB3 Cameras: 355439393
device_link_throughput_limits: [355439393] 
