name: Build Noetic

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          rosdistro: 'noetic'

      - name: Install package dependencies
        run: sudo apt-get update && rosdep update && rosdep install --from-paths src --ignore-src -r -y

      - name: Build package
        run: catkin build
